import React, { useContext, useEffect, useState } from "react";
import axios from "axios";
import { AppContent } from "../../context/AppContext";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import {
  Package,
  Loader2,
  Search,
  Eye,
  Download,
  FileText,
  Calendar,
  X,
} from "lucide-react";
import StatusStamp from "../../components/ui/StatusStamp";

const FinancePaymentBatches = () => {
  const { backendUrl } = useContext(AppContent);
  const navigate = useNavigate();

  const [batches, setBatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [reportModal, setReportModal] = useState(null);

  useEffect(() => {
    fetchBatches();
  }, []);

  const fetchBatches = async () => {
    try {
      axios.defaults.withCredentials = true;
      const { data } = await axios.get(backendUrl + "/api/finance/batches");
      if (data.success) {
        setBatches(data.batches);
      }
    } catch (error) {
      console.error("Failed to fetch batches", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadCsv = async (batchId) => {
    try {
      const response = await axios.get(backendUrl + `/api/finance/batch/${batchId}/csv`, {
        responseType: "blob",
      });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement("a");
      link.href = url;
      link.download = `payment_batch_${batchId}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success("CSV downloaded");
    } catch (error) {
      toast.error("Failed to download CSV");
    }
  };

  const filtered = batches.filter(
    (b) =>
      !search ||
      b.batchId?.toLowerCase().includes(search.toLowerCase()) ||
      b.parentBatchId?.toLowerCase().includes(search.toLowerCase()) ||
      b.generatedBy?.fullName?.toLowerCase().includes(search.toLowerCase())
  );

  const totalAmount = batches.reduce((sum, b) => sum + (b.totalAmount || 0), 0);
  const totalStudents = batches.reduce((sum, b) => sum + (b.totalStudents || 0), 0);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh] bg-[#FAF8F3]">
        <Loader2 className="w-8 h-8 animate-spin text-[#16213E]" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#FAF8F3] text-[#16213E] font-sans pb-12">
      {/* Header */}
      <div className="bg-[#FFFEFB] border-b border-[#DCD6C8] px-8 py-10 mb-8 flex flex-col items-center justify-center text-center shadow-sm">
        <p className="font-mono-data text-xs text-[#B8860B] tracking-widest uppercase mb-3">PMSSS · Finance</p>
        <h1 className="font-serif-display text-4xl text-[#16213E]">Payment Batches</h1>
        <p className="font-mono-data text-sm text-[#16213E]/60 mt-3">View and manage all payment batch history</p>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Ledger Summary Strip */}
        <div className="bg-[#FFFEFB] border border-[#DCD6C8] rounded-sm flex flex-col sm:flex-row divide-y sm:divide-y-0 sm:divide-x divide-[#DCD6C8] mb-8 shadow-sm">
          <div className="flex-1 p-5 text-center">
            <p className="font-serif-display text-3xl text-[#16213E] mb-1">{batches.length}</p>
            <p className="font-mono-data text-xs text-[#16213E]/60 uppercase tracking-widest">Total Batches</p>
          </div>
          <div className="flex-1 p-5 text-center">
            <p className="font-serif-display text-3xl text-[#16213E] mb-1">{totalStudents}</p>
            <p className="font-mono-data text-xs text-[#16213E]/60 uppercase tracking-widest">Students Processed</p>
          </div>
          <div className="flex-1 p-5 text-center">
            <p className="font-mono-data text-3xl text-[#16213E] mb-1">₹{totalAmount.toLocaleString("en-IN")}</p>
            <p className="font-mono-data text-xs text-[#16213E]/60 uppercase tracking-widest">Total Amount</p>
          </div>
        </div>

        {/* Search */}
        <div className="relative mb-6">
          <Search className="absolute left-0 top-1/2 -translate-y-1/2 w-4 h-4 text-[#16213E]/40" />
          <input
            type="text"
            placeholder="Search by batch ID or generated by..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-8 pr-4 py-2 border-0 border-b border-[#DCD6C8] bg-transparent text-sm focus:outline-none focus:border-[#16213E] focus:ring-0 font-mono-data placeholder-[#16213E]/40"
          />
        </div>

        {/* Table */}
        {filtered.length === 0 ? (
          <div className="text-center py-16 bg-[#FFFEFB] rounded-sm border border-[#DCD6C8]">
            <Package className="w-10 h-10 text-[#16213E]/20 mx-auto mb-3" />
            <p className="text-[#16213E]/60 font-mono-data text-sm uppercase tracking-widest">No payment batches found</p>
          </div>
        ) : (
          <div className="bg-[#FFFEFB] rounded-sm border border-[#DCD6C8] overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="bg-[#FAF8F3] border-b border-[#DCD6C8]">
                    <th className="px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Batch ID</th>
                    <th className="px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Parent Batch</th>
                    <th className="px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Generated Date</th>
                    <th className="text-center px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Students</th>
                    <th className="text-right px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Total Amount</th>
                    <th className="px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Status</th>
                    <th className="text-right px-6 py-4 text-xs font-mono-data text-[#16213E]/50 uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#DCD6C8]">
                  {filtered.map((batch) => (
                    <tr key={batch._id} className="hover:bg-[#FAF8F3] transition-colors">
                      <td className="px-6 py-4 text-sm font-mono-data font-semibold text-[#16213E]">{batch.batchId}</td>
                      <td className="px-6 py-4 text-sm">
                        {batch.parentBatchId ? (
                          <button
                            onClick={() => navigate(`/finance/batch/${batch.parentBatchId}`)}
                            className="text-[#16213E] hover:text-[#B8860B] underline font-mono-data text-xs transition-colors"
                          >
                            {batch.parentBatchId}
                          </button>
                        ) : (
                          <span className="text-[#16213E]/40">—</span>
                        )}
                      </td>
                      <td className="px-6 py-4 text-sm text-[#16213E]/70">
                        <div className="flex items-center gap-1.5">
                          <Calendar className="w-3.5 h-3.5 text-[#16213E]/40" />
                          <span className="font-mono-data">
                            {batch.generatedAt ? new Date(batch.generatedAt).toLocaleDateString("en-IN", {
                              day: "2-digit",
                              month: "short",
                              year: "numeric",
                            }) : "—"}
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm text-[#16213E] text-center font-mono-data">{batch.totalStudents}</td>
                      <td className="px-6 py-4 text-sm text-[#16213E] text-right font-mono-data font-medium">
                        ₹{(batch.totalAmount || 0).toLocaleString("en-IN")}
                      </td>
                      <td className="px-6 py-4">
                        <div className="scale-75 origin-left">
                          <StatusStamp status={batch.status} />
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center justify-end gap-2">
                          <button
                            onClick={() => navigate(`/finance/batch/${batch.batchId}`)}
                            className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#16213E] text-[#16213E] hover:bg-[#16213E] hover:text-[#FFFEFB] rounded-sm text-xs font-mono-data uppercase tracking-wider transition-colors"
                            title="View Details"
                          >
                            <Eye className="w-3.5 h-3.5" />
                            View
                          </button>
                          <button
                            onClick={() => handleDownloadCsv(batch.batchId)}
                            className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#16213E]/30 text-[#16213E]/70 hover:border-[#16213E] hover:text-[#16213E] rounded-sm text-xs font-mono-data uppercase tracking-wider transition-colors"
                            title="Download CSV"
                          >
                            <Download className="w-3.5 h-3.5" />
                            CSV
                          </button>
                          {batch.status === "Completed" && (
                            <button
                              onClick={() => setReportModal(batch)}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#2F6F4F] text-[#2F6F4F] hover:bg-[#2F6F4F] hover:text-[#FFFEFB] rounded-sm text-xs font-mono-data uppercase tracking-wider transition-colors"
                              title="Payment Report"
                            >
                              <FileText className="w-3.5 h-3.5" />
                              Report
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>

      {/* Payment Report Modal */}
      {reportModal && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-[#FFFEFB] border border-[#DCD6C8] rounded-sm w-full max-w-lg p-6 max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-serif-display text-[#16213E]">Payment Report</h3>
              <button onClick={() => setReportModal(null)} className="text-[#16213E]/40 hover:text-[#16213E] transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-4 mb-6 pb-6 border-b border-[#DCD6C8]">
              <div className="flex justify-between text-sm">
                <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Batch ID</span>
                <span className="font-mono-data font-semibold text-[#16213E]">{reportModal.batchId}</span>
              </div>
              {reportModal.parentBatchId && (
                <div className="flex justify-between text-sm">
                  <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Retry of</span>
                  <span className="font-mono-data text-[#16213E]">{reportModal.parentBatchId}</span>
                </div>
              )}
              <div className="flex justify-between text-sm">
                <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Generated By</span>
                <span className="text-[#16213E] text-sm">{reportModal.generatedBy?.fullName || "—"}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Date</span>
                <span className="text-[#16213E] font-mono-data">
                  {reportModal.generatedAt ? new Date(reportModal.generatedAt).toLocaleString("en-IN") : "—"}
                </span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Total Students</span>
                <span className="font-mono-data font-semibold text-[#16213E]">{reportModal.totalStudents}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-[#16213E]/60 font-mono-data uppercase tracking-wider text-xs">Total Amount</span>
                <span className="font-mono-data font-semibold text-[#16213E]">₹{(reportModal.totalAmount || 0).toLocaleString("en-IN")}</span>
              </div>
            </div>

            <div className="grid grid-cols-3 gap-0 border border-[#DCD6C8] divide-x divide-[#DCD6C8] mb-6 rounded-sm">
              <div className="bg-[#FFFEFB] p-4 text-center">
                <p className="text-xl font-mono-data font-bold text-[#2F6F4F] mb-1">
                  {reportModal.applications?.filter((a) => a.paymentStatus === "Paid").length || 0}
                </p>
                <p className="text-xs font-mono-data uppercase tracking-wider text-[#16213E]/60">Paid</p>
              </div>
              <div className="bg-[#FFFEFB] p-4 text-center">
                <p className="text-xl font-mono-data font-bold text-[#8B2E2E] mb-1">
                  {reportModal.applications?.filter((a) => a.paymentStatus === "Failed").length || 0}
                </p>
                <p className="text-xs font-mono-data uppercase tracking-wider text-[#16213E]/60">Failed</p>
              </div>
              <div className="bg-[#FFFEFB] p-4 text-center">
                <p className="text-xl font-mono-data font-bold text-[#B8860B] mb-1">
                  {reportModal.applications?.filter((a) => a.paymentStatus === "Pending").length || 0}
                </p>
                <p className="text-xs font-mono-data uppercase tracking-wider text-[#16213E]/60">Pending</p>
              </div>
            </div>

            <div className="flex justify-end">
              <button
                onClick={() => {
                  window.print();
                }}
                className="px-5 py-2 bg-[#16213E] hover:bg-[#0F1729] text-[#FFFEFB] rounded-sm text-xs font-mono-data uppercase tracking-wider transition-colors"
              >
                Print Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FinancePaymentBatches;
